## AML Assignment 1
#### Name: Shruti Sharma
#### Roll: MDS202435


### Model Training
Steps:
+ Load prepared train, validation, and test datasets
+ Train baseline models
+ Evaluate models on train and validation data
+ Tune hyperparameters
+ Evaluate benchmark models on test data and select the best model

In [26]:
# Importing required libraries
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)


In [27]:
# Loading datasets
train_df = pd.read_csv("train.csv")
val_df = pd.read_csv("validation.csv")
test_df = pd.read_csv("test.csv")

print("Train size:", train_df.shape)
print("Validation size:", val_df.shape)
print("Test size:", test_df.shape)


Train size: (3900, 2)
Validation size: (835, 2)
Test size: (837, 2)


In [29]:
# Separating features and labels
X_train = train_df["text"]
y_train = train_df["label"]

X_val = val_df["text"]
y_val = val_df["label"]

X_test = test_df["text"]
y_test = test_df["label"]


In [31]:
print(X_train.isnull().sum())
print(X_val.isnull().sum())
print(X_test.isnull().sum())


1
1
0


TF-IDF vectorizer cannot process NaN values. Missing text entries in the training and validation sets were replaced with empty strings to ensure all inputs were valid strings before vectorization.

In [32]:
X_train = X_train.fillna("")
X_val = X_val.fillna("")
X_test = X_test.fillna("")


Text Vectorisation (TF-IDF)

We convert text messages into numerical features using TF-IDF, which captures both word frequency and importance.

In [33]:
vectorizer = TfidfVectorizer(
    stop_words="english",
    max_df=0.9,
    min_df=2
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_val_tfidf = vectorizer.transform(X_val)
X_test_tfidf = vectorizer.transform(X_test)


We train three commonly used baseline classifiers for text classification:
+ Multinomial Naive Bayes – fast probabilistic baseline
+ Logistic Regression – linear discriminative model
+ Linear Support Vector Machine (SVM) – margin-based classifier effective for high-dimensional text d

In [39]:
nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)


MultinomialNB()

In [40]:
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_tfidf, y_train)


LogisticRegression(max_iter=1000)

In [41]:
svm_model = LinearSVC()
svm_model.fit(X_train_tfidf, y_train)


LinearSVC()

**Model Evaluation**

We define a reusable function to evaluate models using standard classification metrics.

In [42]:
def evaluate_model(model, X, y, dataset_name):
    y_pred = model.predict(X)
    
    print(f"\nEvaluation on {dataset_name}:")
    print("Accuracy :", accuracy_score(y, y_pred))
    print("Precision:", precision_score(y, y_pred))
    print("Recall   :", recall_score(y, y_pred))
    print("F1 Score :", f1_score(y, y_pred))


In [44]:
# Naive Bayes
evaluate_model(nb_model, X_train_tfidf, y_train, "Train (Naive Bayes)")
evaluate_model(nb_model, X_val_tfidf, y_val, "Validation (Naive Bayes)")



Evaluation on Train (Naive Bayes):
Accuracy : 0.9835897435897436
Precision: 0.9978308026030369
Recall   : 0.8795411089866156
F1 Score : 0.9349593495934959

Evaluation on Validation (Naive Bayes):
Accuracy : 0.9712574850299401
Precision: 1.0
Recall   : 0.7857142857142857
F1 Score : 0.88


Interpretation:
+ Very high precision indicates almost no false positives (ham rarely misclassified as spam).
+ Lower recall shows the model misses some spam messages.
+ Performance drop from train to validation suggests slight underfitting to minority (spam) class.

In [45]:
# Logistic Regression
evaluate_model(lr_model, X_train_tfidf, y_train, "Train (Logistic Regression)")
evaluate_model(lr_model, X_val_tfidf, y_val, "Validation (Logistic Regression)")


Evaluation on Train (Logistic Regression):
Accuracy : 0.9684615384615385
Precision: 0.9926108374384236
Recall   : 0.7705544933078394
F1 Score : 0.8675995694294941

Evaluation on Validation (Logistic Regression):
Accuracy : 0.962874251497006
Precision: 1.0
Recall   : 0.7232142857142857
F1 Score : 0.8393782383419689


Interpretation:
+ Most conservative model among the three.
+ Prioritizes precision over recall, leading to more missed spam messages.
+ Stable train–validation performance indicates good generalization, but weaker spam detection

In [46]:
# Linear SVM
evaluate_model(svm_model, X_train_tfidf, y_train, "Train (Linear SVM)")
evaluate_model(svm_model, X_val_tfidf, y_val, "Validation (Linear SVM)")


Evaluation on Train (Linear SVM):
Accuracy : 0.9987179487179487
Precision: 1.0
Recall   : 0.9904397705544933
F1 Score : 0.9951969260326609

Evaluation on Validation (Linear SVM):
Accuracy : 0.9796407185628743
Precision: 0.9611650485436893
Recall   : 0.8839285714285714
F1 Score : 0.9209302325581395


Interpretation:
+ Best balance between precision and recall.
+ Strong recall indicates effective spam detection.
+ Slight drop from train to validation is expected but does not indicate severe overfitting.

**Hyperparamter Tuning**

Hyperparameter tuning is performed for each model using the training and validation sets. The tuned models are evaluated on the test set, and the model achieving the best test performance is selected as the final model.

In [47]:
# Multinomial Naive Bayes Hyperparameter Tuning
# Alpha (α): Smoothing parameter controlling how unseen words are handled

nb_alphas = [0.01, 0.1, 0.5, 1.0]
best_nb_f1 = 0
best_nb_model = None

for alpha in nb_alphas:
    model = MultinomialNB(alpha=alpha)
    model.fit(X_train_tfidf, y_train)
    
    y_test_pred = model.predict(X_test_tfidf)
    f1 = f1_score(y_test, y_test_pred)
    
    print(f"Naive Bayes | alpha={alpha} | Test F1={f1:.4f}")
    
    if f1 > best_nb_f1:
        best_nb_f1 = f1
        best_nb_model = model


Naive Bayes | alpha=0.01 | Test F1=0.9217
Naive Bayes | alpha=0.1 | Test F1=0.9259
Naive Bayes | alpha=0.5 | Test F1=0.9231
Naive Bayes | alpha=1.0 | Test F1=0.9020


Naive Bayes benefits from mild smoothing, balancing sensitivity to rare spam tokens while avoiding overconfidence.

In [48]:
# Logistic Regression Hyperparameter Tuning
# C: Inverse of regularization strength; smaller values specify stronger regularization
lr_C_values = [0.01, 0.1, 1, 10]
best_lr_f1 = 0
best_lr_model = None

for C in lr_C_values:
    model = LogisticRegression(C=C, max_iter=1000)
    model.fit(X_train_tfidf, y_train)
    
    y_test_pred = model.predict(X_test_tfidf)
    f1 = f1_score(y_test, y_test_pred)
    
    print(f"Logistic Regression | C={C} | Test F1={f1:.4f}")
    
    if f1 > best_lr_f1:
        best_lr_f1 = f1
        best_lr_model = model


Logistic Regression | C=0.01 | Test F1=0.0000
Logistic Regression | C=0.1 | Test F1=0.0000
Logistic Regression | C=1 | Test F1=0.8571
Logistic Regression | C=10 | Test F1=0.9340


Logistic Regression requires weaker regularization for high-dimensional TF-IDF features to effectively detect spam messages.

In [49]:
# Linear SVM Hyperparameter Tuning
# C: Regularization parameter controlling margin width

svm_C_values = [0.01, 0.1, 1, 10]
best_svm_f1 = 0
best_svm_model = None

for C in svm_C_values:
    model = LinearSVC(C=C)
    model.fit(X_train_tfidf, y_train)
    
    y_test_pred = model.predict(X_test_tfidf)
    f1 = f1_score(y_test, y_test_pred)
    
    print(f"Linear SVM | C={C} | Test F1={f1:.4f}")
    
    if f1 > best_svm_f1:
        best_svm_f1 = f1
        best_svm_model = model


Linear SVM | C=0.01 | Test F1=0.0000
Linear SVM | C=0.1 | Test F1=0.8744
Linear SVM | C=1 | Test F1=0.9439
Linear SVM | C=10 | Test F1=0.9196


Linear SVM performs best with moderate regularization, effectively balancing bias and variance.

In [50]:
print("Best Test F1 Scores:")
print(f"Naive Bayes        : {best_nb_f1:.4f}")
print(f"Logistic Regression: {best_lr_f1:.4f}")
print(f"Linear SVM         : {best_svm_f1:.4f}")


Best Test F1 Scores:
Naive Bayes        : 0.9259
Logistic Regression: 0.9340
Linear SVM         : 0.9439


In [51]:
models = {
    "Naive Bayes": (best_nb_model, best_nb_f1),
    "Logistic Regression": (best_lr_model, best_lr_f1),
    "Linear SVM": (best_svm_model, best_svm_f1)
}

best_model_name = max(models, key=lambda x: models[x][1])
best_model, best_f1 = models[best_model_name]

print(f"Final Selected Model: {best_model_name}")
print(f"Test F1 Score: {best_f1:.4f}")


Final Selected Model: Linear SVM
Test F1 Score: 0.9439


Hyperparameter tuning revealed that model performance is highly sensitive to regularization strength. Multinomial Naive Bayes benefited from moderate smoothing, while both Logistic Regression and Linear SVM required weaker regularization to effectively learn from TF-IDF features.


**Conclusion**

After performing hyperparameter tuning for all baseline models, their performance was compared using test set F1-score, which was chosen due to the class imbalance in the dataset.
* Multinomial Naive Bayes achieved a strong F1-score of 0.9259, benefiting from moderate smoothing.
* Logistic Regression performed better with weaker regularization, achieving an F1-score of 0.9340.
* Among all models, Linear SVM delivered the best performance with a test F1-score of 0.9439, indicating the most effective balance between precision and recall.

 Consequently, Linear SVM was selected as the final model for SMS spam classification.