#!/bin/sh

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
    echo "Running tests before commit..."

    python -m pytest test.py

    if [ $? -ne 0 ]; then
        echo "Tests failed. Commit aborted."
        exit 1
    fi

    echo "Tests passed. Commit allowed."
fi